export const ROUTE_LANDING_PAGE = "/";
export const ROUTE_VIDEO_PAGE = "/video";
export const ROUTE_ERROR_PAGE = "*";

export const MICROPHONE_LOADING = "MICROPHONE_LOADING";
export const MICROPHONE_AVAILABLE = "MICROPHONE_AVAILABLE";
export const MICROPHONE_ERROR = "MICROPHONE_ERROR";
export const MICROPHONE_CONNECTED = "MICROPHONE_CONNECTED";
export const MICROPHONE_DISCONNECTED = "MICROPHONE_DISCONNECTED";