export const ROUTE_LANDING_PAGE = "/";
export const ROUTE_VIDEO_PAGE = "/video";
export const ROUTE_AUDIO_PAGE = "/audio";
export const ROUTE_GOOGLE_AUTH_PAGE = "/google-auth";
export const ROUTE_GOOGLE_AUTH_REDIRECT = "/api/sessions/oauth/google-redirect";
export const ROUTE_ERROR_PAGE = "*";

export const MICROPHONE_LOADING = "MICROPHONE_LOADING";
export const MICROPHONE_AVAILABLE = "MICROPHONE_AVAILABLE";
export const MICROPHONE_ERROR = "MICROPHONE_ERROR";
export const MICROPHONE_CONNECTED = "MICROPHONE_CONNECTED";
export const MICROPHONE_DISCONNECTED = "MICROPHONE_DISCONNECTED";

export const CAMERA_LOADING = "CAMERA_LOADING";
export const CAMERA_AVAILABLE = "CAMERA_AVAILABLE";
export const CAMERA_RECORDING_STARTED = "CAMERA_RECORDING_STARTED";
export const CAMERA_RECORDING_STOPPED = "CAMERA_RECORDING_STOPPED";
export const CAMERA_RECORDING_COMPLETED = "CAMERA_RECORDING_COMPLETED";
export const CAMERA_ERROR = "CAMERA_ERROR";
export const CAMERA_CONNECTED = "CAMERA_CONNECTED";
export const CAMERA_DISCONNECTED = "CAMERA_DISCONNECTED";
export const CAMERA_RECORDING_DURATION_MS = 15000;

export const BUTTON_AUDIO_REC = "RECORD AUDIO"
export const BUTTON_VIDEO_REC = "RECORD VIDEO"
export const BUTTON_AUDIO_PERMISSION = "GET MIC PERMISSION"
export const BUTTON_VIDEO_PERMISSION = "GET CAM PERMISSION"
export const BUTTON_AUDIO_REC_START = "START AUDIO REC"
export const BUTTON_AUDIO_REC_STOP = "STOP AUDIO REC"
export const BUTTON_VIDEO_REC_START = "START VIDEO REC"
export const BUTTON_VIDEO_REC_STOP = "STOP VIDEO REC"
export const BUTTON_VIDEO_UPLOAD = "STOP VIDEO REC"
export const BUTTON_GO_HOME = "GO HOME"

export const BUTTON_GOOGLE_AUTH_LOGIN = "CLICK TO LOGIN"